#!/usr/bin/env ruby
# USAGE: 
# 
# ruby script/gruler_daemon run     -- start the daemon and stay on top
# ruby script/gruler_daemon start   -- start the daemon in the background
# ruby script/gruler_daemon stop    -- stop the daemon
# ruby script/gruler_daemon restart -- stop the daemon and restart it afterwards

ENV["RAILS_ENV"] ||= "development"

require 'rubygems'
require 'ap'
require 'ruby-debug'
require 'daemons'

root_dir = "."
root_dir = Rails.root if defined?(Rails)

pid_dir = File.join(root_dir, "tmp")

app_options = { 
  :dir_mode => :normal,
  :dir => pid_dir,
  :multiple => false,
  :backtrace => true,
  :log_output => true
}

Daemons.run_proc("gruler_daemon", app_options) do
  if defined?(Rails)
    require File.join(root_dir, "/config/environment")
    puts "Loaded #{Rails.env} environment"
  end
  require 'gruler'
  require 'gruler/runner'
  require 'gruler/core'
  require 'eventmachine'
  require 'em-websocket'

  Gruler::Runner.new.run
end

